# Generated by Django 3.2.19 on 2023-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
